version: "3.5"
services:
  service_api:
    build: .
    environment:
      - MODE=dev
      - POSTGRES_HOST=host.docker.internal
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql
volumes:
  dbdata: